# Generated by bower2nix v3.2.0 (https://github.com/rvl/bower2nix)
{ fetchbower, buildEnv }:
buildEnv { name = "bower-env"; ignoreCollisions = true; paths = [
  (fetchbower "purescript-prelude" "3.1.1" "~3.1.0" "0zdwf4755ifq19227w588719sdhq4sw6qnng8jq8zwnhz2kwv4gb")
]; }
