# This file has been generated by node2nix 1.4.0. Do not edit!

{nodeEnv, fetchurl, fetchgit, globalBuildInputs ? []}:

let
  sources = {};
in
{
  "typescript-2.4.1" = nodeEnv.buildNodePackage {
    name = "typescript";
    packageName = "typescript";
    version = "2.4.1";
    src = fetchurl {
      url = "https://registry.npmjs.org/typescript/-/typescript-2.4.1.tgz";
      sha1 = "c3ccb16ddaa0b2314de031e7e6fee89e5ba346bc";
    };
    buildInputs = globalBuildInputs;
    meta = {
      description = "TypeScript is a language for application scale JavaScript development";
      homepage = http://typescriptlang.org/;
      license = "Apache-2.0";
    };
    production = true;
  };
}